### ISSUE TITLE
PR: enfore TUN as network interface and reverse-proxy

### ISSUE THREAD

**Issue by JOduMonT** [guillaumedsde/alpine-qbittorrent-openvpn#28]
### 1. for an easier security, it might be worth it to enforce the connection only through TUN

![image](https://user-images.githubusercontent.com/5204724/97066173-7a600180-15dd-11eb-96a6-7dc62aca5c98.png)

which could be hardcoded in ./qBittorrent/qBittorrent.conf
```
[Preferences]
Connection\Interface=tun1
Connection\InterfaceName=tun1
```

### 2. I didn't know how to write it in the README, and or if it was appropriate, but this container work well with the reverse proxy config proposed by linux-server with their container SWAG
https://github.com/linuxserver/reverse-proxy-confs

**Comment by guillaumedsde** [comment]
Hi,

Good to know that the container works well with the lsio reverse proxy :)  , personally I use traefik: [this is my full `docker-compose.yml` if you're interested](https://gitlab.com/guillaumedsde/docker-media-stack).

Regarding hardcoding the interface in the qbittorrent configuration, I did [something similar](https://github.com/guillaumedsde/docker-qbittorrent-openvpn/blob/164b49020fbe17b0b4ca276a937175e5e404ca5a/transmission/settings.tmpl#L16) in my previous container but since the firewall rules forbid any traffic outside the VPN tunnel this is not necessary, it could be a nice failsafe, but if for any reason the VPN interface is anything other than `tun1` (although it shouldn't) then qbittorrent would not have internet access even if the firewall rules prevent access outside the tunnel

**Comment by JOduMonT** [comment]
> Good to know that the container works well with the lsio reverse proxy :) , personally I use traefik: [this is my full `docker-compose.yml` if you're interested](https://gitlab.com/guillaumedsde/docker-media-stack).

@guillaumedsde I'm curious; why do you like/prefer traefik over haproxy or nginx ?
