### ISSUE TITLE
Slow speeds with Torguard

### ISSUE THREAD

**Issue by reconman** [guillaumedsde/alpine-qbittorrent-openvpn#46]
## Information
In the docker container, I only get 1.5 MB/s, suddenly. At some point today I reached 10 MB/s, but now I can't get above 1.5 MB/s.

I see the limited speed both when I'm torrenting and when I execute some `wget` commands to download files from speedtest websites.

It's definitely not the VPN provider's fault, as I can get 10 MB/s with the exact same VPN settings in the docker-transmission-openvpn container.

## Current setup
Tag `latest`, digest `sha256:0f5eea4cd0c73b7d66d73dcefcc6b3c97e63dd5269c3bd1904691a94cc80e9dd`

## `docker-compose.yml` file or `docker run` command
```
docker run --name=qbittorrent --hostname=qbittorrent \
    --cap-add=NET_ADMIN -d -v /volume1/Data/Downloads/Torrents/:/downloads \
    -v=/volume1/homes/qbittorrent/Austria.ovpn:/etc/openvpn/torguard/Austria.ovpn:ro \
    -v /volume1/docker/qbittorrent:/config \
    -v /etc/localtime:/etc/localtime:ro \
    -e DNS=1.1.1.1 \
    -e OPENVPN_PROVIDER=torguard \
    -e OPENVPN_CONFIG=Austria \
    -e OPENVPN_USERNAME=removed \
    -e OPENVPN_PASSWORD=removed \
    -e PUID=1032 \
    -e PGID=65537 \
    -e LAN=192.168.0.0/16 \
    -p 8080:8080 \
    --label='autoheal=true' \
    --network=mediaNet \
    --restart=always \
    guillaumedsde/alpine-qbittorrent-openvpn:latest
```

## Attempted Fix(es)

I tried restarting the container a few times, but it didn't help.

**Comment by guillaumedsde** [comment]
Hum, this is strange especially if the other container you tried is @haugene [docker-transmission-openvpn](https://github.com/haugene/docker-transmission-openvpn) since he is using the same alpine base image and the same openvpn binary.

Could you confirm you can't reproduce this issue in haugene's container when:
- using the same OpenVPN configuration 
- using the same OpenVPN server (sometimes a configuration randomely picks a server)
- at roughly the same time (so we're sure its not an OpenVPN server)

**Comment by reconman** [comment]
I was actually able to reproduce this behavior yesterday. I think I was able to fix the problem by changing the OpenVPN connection from UDP to TCP. At that point, I got normal speeds again.

The limited speeds happen randomly.

I'll try out the qbittorrent container the next time I have to download something big. For now the main reason against using qbittorrent for me is that I'm still searching for a desktop app similar to Transmission Remote GUI.

**Comment by guillaumedsde** [comment]
good to hear, sometimes ISP configurations do weird stuff to OpenVPN traffic, might be worth trying on a different ISP (by using a wifi hotspot?)

regarding the UI, yeah deluge and transmission's remote ui features are nice, personally I use the [flood webUI](https://github.com/jesec/flood) for better interface to qBittorrent (mainly because its phone friendly) its still in beta for qBittorrent but works well enough if you want a configuration for it here's [my docker-compose.yml](https://gitlab.com/guillaumedsde/docker-media-stack/-/blob/master/docker-compose.yml#L160)
